// packages/web-shared/src/components/react/Button.tsx
import React, { ButtonHTMLAttributes } from 'react';
import { Icon } from './Icon';

export type ButtonVariant = 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'link';
export type ButtonSize = 'sm' | 'md' | 'lg';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  icon?: string;
  iconPosition?: 'left' | 'right';
  loading?: boolean;
  block?: boolean;
}

/**
 * React按钮组件
 */
export const Button: React.FC<ButtonProps> = ({
  children,
  variant = 'primary',
  size = 'md',
  icon,
  iconPosition = 'left',
  loading = false,
  block = false,
  disabled = false,
  className = '',
  ...rest
}) => {
  // 基础类名
  const baseClass = 'hs-button';
  
  // 变体类名
  const variantClass = `${baseClass}--${variant}`;
  
  // 尺寸类名
  const sizeClass = `${baseClass}--${size}`;
  
  // 块级类名
  const blockClass = block ? `${baseClass}--block` : '';
  
  // 加载类名
  const loadingClass = loading ? `${baseClass}--loading` : '';
  
  // 禁用状态
  const isDisabled = disabled || loading;
  
  // 计算最终类名
  const buttonClass = `${baseClass} ${variantClass} ${sizeClass} ${blockClass} ${loadingClass} ${className}`.trim();
  
  // 图标元素
  const iconElement = (loading || icon) ? (
    <span className={`${baseClass}__icon ${baseClass}__icon--${iconPosition}`}>
      <Icon name={loading ? 'spinner' : icon || ''} spin={loading} size={size === 'lg' ? 20 : size === 'sm' ? 14 : 16} />
    </span>
  ) : null;
  
  return (
    <button
      className={buttonClass}
      disabled={isDisabled}
      {...rest}
    >
      {iconPosition === 'left' && iconElement}
      {children && <span className={`${baseClass}__text`}>{children}</span>}
      {iconPosition === 'right' && iconElement}
    </button>
  );
};

// packages/web-shared/src/components/vue/Button.vue
<template>
  <button
    :class="[
      'hs-button',
      `hs-button--${variant}`,
      `hs-button--${size}`,
      { 'hs-button--block': block },
      { 'hs-button--loading': loading },
      className
    ]"
    :disabled="disabled || loading"
    v-bind="$attrs"
  >
    <span v-if="(loading || icon) && iconPosition === 'left'" :class="`hs-button__icon hs-button__icon--${iconPosition}`">
      <Icon :name="loading ? 'spinner' : icon" :spin="loading" :size="iconSize" />
    </span>
    <span v-if="$slots.default" class="hs-button__text">
      <slot></slot>
    </span>
    <span v-if="(loading || icon) && iconPosition === 'right'" :class="`hs-button__icon hs-button__icon--${iconPosition}`">
      <Icon :name="loading ? 'spinner' : icon" :spin="loading" :size="iconSize" />
    </span>
  </button>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';
import { Icon } from './Icon.vue';

export default defineComponent({
  name: 'Button',
  components: {
    Icon,
  },
  props: {
    variant: {
      type: String,
      default: 'primary',
      validator: (value: string) => ['primary', 'secondary', 'success', 'warning', 'danger', 'link'].includes(value),
    },
    size: {
      type: String,
      default: 'md',
      validator: (value: string) => ['sm', 'md', 'lg'].includes(value),
    },
    icon: {
      type: String,
      default: '',
    },
    iconPosition: {
      type: String,
      default: 'left',
      validator: (value: string) => ['left', 'right'].includes(value),
    },
    loading: {
      type: Boolean,
      default: false,
    },
    block: {
      type: Boolean,
      default: false,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
    className: {
      type: String,
      default: '',
    },
  },
  setup(props) {
    const iconSize = computed(() => {
      if (props.size === 'lg') return 20;
      if (props.size === 'sm') return 14;
      return 16;
    });

    return {
      iconSize,
    };
  },
});
</script>

<style scoped>
/* 基础按钮样式将在全局CSS中定义 */
</style>
