// packages/web-shared/src/components/vue/Alert.vue
<template>
  <div :class="['hs-alert', `hs-alert--${type}`, className]" :style="style" role="alert">
    <div v-if="showIcon" class="hs-alert__icon">
      <Icon :name="iconName" :size="16" />
    </div>
    <div class="hs-alert__content">
      <div v-if="title" class="hs-alert__title">{{ title }}</div>
      <div class="hs-alert__message">{{ message }}</div>
    </div>
    <button 
      v-if="closable" 
      class="hs-alert__close" 
      @click="handleClose"
      aria-label="Close"
    >
      <Icon name="close" :size="14" />
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';
import { Icon } from './Icon.vue';

type AlertType = 'info' | 'success' | 'warning' | 'error';

export default defineComponent({
  name: 'Alert',
  components: {
    Icon,
  },
  props: {
    type: {
      type: String as () => AlertType,
      default: 'info',
      validator: (value: string) => ['info', 'success', 'warning', 'error'].includes(value),
    },
    title: {
      type: String,
      default: '',
    },
    message: {
      type: String,
      required: true,
    },
    showIcon: {
      type: Boolean,
      default: true,
    },
    closable: {
      type: Boolean,
      default: false,
    },
    className: {
      type: String,
      default: '',
    },
    style: {
      type: Object,
      default: () => ({}),
    },
  },
  emits: ['close'],
  setup(props, { emit }) {
    // 图标映射
    const iconMap = {
      info: 'info',
      success: 'check',
      warning: 'warning',
      error: 'close',
    };
    
    // 选择对应的图标
    const iconName = computed(() => iconMap[props.type as AlertType]);
    
    // 关闭事件处理
    const handleClose = () => {
      emit('close');
    };
    
    return {
      iconName,
      handleClose,
    };
  },
});
</script>

<style scoped>
/* 基础警告提示样式将在全局CSS中定义 */
</style>

// packages/web-shared/src/components/react/Alert.tsx
import React from 'react';
import { Icon } from './Icon';

export type AlertType = 'info' | 'success' | 'warning' | 'error';

export interface AlertProps {
  type?: AlertType;
  title?: string;
  message: string;
  showIcon?: boolean;
  closable?: boolean;
  onClose?: () => void;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * React警告提示组件
 */
export const Alert: React.FC<AlertProps> = ({
  type = 'info',
  title,
  message,
  showIcon = true,
  closable = false,
  onClose,
  className = '',
  style,
}) => {
  // 基础类名
  const baseClass = 'hs-alert';
  
  // 类型类名
  const typeClass = `${baseClass}--${type}`;
  
  // 计算最终类名
  const alertClass = `${baseClass} ${typeClass} ${className}`.trim();
  
  // 图标映射
  const iconMap: Record<AlertType, string> = {
    info: 'info',
    success: 'check',
    warning: 'warning',
    error: 'close',
  };
  
  // 选择对应的图标
  const iconName = iconMap[type];
  
  return (
    <div className={alertClass} style={style} role="alert">
      {showIcon && (
        <div className={`${baseClass}__icon`}>
          <Icon name={iconName} size={16} />
        </div>
      )}
      <div className={`${baseClass}__content`}>
        {title && <div className={`${baseClass}__title`}>{title}</div>}
        <div className={`${baseClass}__message`}>{message}</div>
      </div>
      {closable && (
        <button 
          className={`${baseClass}__close`}
          onClick={onClose}
          aria-label="Close"
        >
          <Icon name="close" size={14} />
        </button>
      )}
    </div>
  );
};
